import random
Random = random.randint(1, 9)

# random library is called

def ErrorHandling():
    global Num
    while True:
        try:
            Num = int(input())
            break
        except ValueError:
            print("Please make sure to only enter Integers")
        except:
            print("Unknown error occured. Try again with a different number")

# Function to handle any input errors + this is where the user inputs the Number variable

Pass = 0 # Variable used for displaying the stats properly (not important)
Count = 0
Num = None

# Variables are initialised

print(f"{" " * 14}+----------------------------------------+")
greeting = "Welcome to the \"Guess the Number\" Game"
print(f"{" " * 14}|{" " * 1}{greeting} |")
for i in range(1):
    print(f"{" "*14}|{" " * 40}|")
    Pass += 1
    if Pass == 1:
        print(f"{" "*14}| Count = {Count} {" " * 17} Num = {Num} |")
print(f"{" " * 14}+----------------------------------------+")
print("""Here are the rules of the game:
1. Guess the Random number (1-9) generated by my awesome program :)
2. Don't forget to have fun while you are at it ;)
""")
print("Please enter a number: ") # Enter the Num variable

# This is what the user see when he/she runs the code

def Display():
    x = 0
    print(f"{" " * 14}+----------------------------------------+")
    print(f"{" " * 14}|{" " * 9}Stats have been updated! {" " * 6}|")
    for i in range(1):
        print(f"{" "*14}|{" " * 40}|")
        x += 1
        if x == 1:
            if Num != None:
                print(f"{" "*14}| Count = {Count} {" " * 20} Num = {Num} |")
            else:
                print(f"{" "*14}| Count = {Count} {" " * 17} Num = {Num} |")
            print(f"{" " * 14}+----------------------------------------+")

# The display function displays the stats of the user i.e. the Count and Num variables

list_of_numbers_used = [] # This list is used to store numbers entered by the user and whenever the user inputs a number twice,this number is checked against the updated list and if found in the list, the Count variable shouldn't increment and instead the user is told to re-enter the Num

ErrorHandling() # User input the Num variable and it gets checked by the function for any input errors

while Num != Random: # Random Number not guessed
    while Num < 1 or Num > 9: # Range validation
        print("Please enter within range")
        ErrorHandling()
    if Num in list_of_numbers_used: # No duplicate numbers validation
        print("This number has already been used before, try again with a new number")
        ErrorHandling()
        continue
    list_of_numbers_used.append(Num)
    if Random > Num: # If the number is lower than the Random
        print("Too low, try again")
        Count += 1
        Display()
    elif Num > Random: # If the number is higher than the Random
        print("Too high, try again")
        Count += 1
        Display()
    ErrorHandling()
if Num == Random: # If the Random Number is guessed correctly
    print("Congrats on Solving the number. Here is your final stats!")
    Count += 1
    Display()